class RoomsErrors:
    ROOM_NOT_FOUND = 'NOT_FOUND'
    ROOM_LIMIT_REACHED = 'LIMIT_REACHED'
    INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'

class ChatErrors:
    EMPTY_MESSAGE = 'EMPTY'
    MUST_BE_IN_ROOM = 'ROOM_IS_NULL'
