class DataErrors:
    NULL = 'NULL_DATA'

class RoomsErrors:
    ROOM_NOT_FOUND = 'NOT_FOUND'
    ROOM_LIMIT_REACHED = 'LIMIT_REACHED'
    INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'
    ROOM_CREATION_NOT_ALLOWED = 'CREATION_NOT_ALLOWED'
    RATELIMIT_REACHED = 'RATELIMIT_REACHED'
    ANOTHER_SESSION_CONNECTED = 'CONNECTED_FROM_ANOTHER_SESSION'
    ALREADY_CONNECTED = 'ALREADY_CONNECTED'

class ChatErrors:
    EMPTY_MESSAGE = 'EMPTY'
    MUST_BE_IN_ROOM = 'ROOM_IS_NULL'

class CryptoErrors:
    INTEGRITY_CHECK_FAILED = 'SAID_INTEGRITY_CHECK_FAILED'
    RSA_ENCRYPTION_FAILED = 'RSA_ENCRYPTION_FAILED'
